import { Footer } from '@/app/(public)/components/footer'
import { Navbar } from '@/app/(public)/components/navbar'
import { Urbanist } from 'next/font/google'
import type { Metadata } from 'next'
import { ModalProvider } from '@/app/(public)/components/providers/modal-provider'

const inter = Urbanist({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Store',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <>
      <ModalProvider />
      <div className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </div>
    </>
  )
}
